config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :profiles do 
  	resources :comments
  end

  resources :resources_page
  resources :about
  

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
	has_many :comments, dependent: :destroy

	has_attached_file :image

	validates :flname, presence: true

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
 
	def create
		@profile = Profile.find(params[:profile_id])
		@comment = @profile.comments.create(comment_params)
		redirect_to profile_path(@profile)
	end

	def destroy 
		@profile = Profile.find(params[:profile_id])
		@comment = @profile.comments.find(params[:id])
		@comment.destroy 
		redirect_to profile_path(@profile)
	end

	private
	def comment_params
		params.require(:comment).permit(:commenter, :body)
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

 	http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
 	
	def index 
		@profiles = Profile.all
	end 

	def show
		@profile = Profile.find(params[:id])
	end

	def new 
		@profile = Profile.new
	end

	def edit 
		@profile = Profile.find(params[:id])
	end

	def create

		@profile = Profile.new(profile_params)


		if @profile.save
			redirect_to @profile
		else 
			render 'new'
		end
	end 

	def update
		@profile = Profile.find(params[:id])

		if @profile.update(profile_params)
			redirect_to @profile
		else
			render 'edit'
		end 
	end

	def destroy
    	@profile = Profile.find(params[:id])
    	@profile.destroy
 
    	redirect_to profiles_path
  end

	private
	def profile_params 
		params.require(:profile).permit(:flname, :subjects, :age, :phonenumber, :email, :experience, :image)
	end
end

app/controllers/resources_page_controller.rb
class ResourcesPageController < ApplicationController
	 def index 

	end 

	def show
		render params[:id]
	end

	def math
		render action: "math"
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/resources_page_helper.rb
module ResourcesPageHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<style>

.comment {
	border: 1px solid black;
	padding: 10px;
}

#name {
	font-style: italic;
	color: gray;
}
</style>

<div class = 'comment'>
<p>
  <div id = 'name'>
  <%= comment.commenter %>
</div>
</p>
 
<p>s
  <%= comment.body %>
</p>

<p>
	<%= link_to 'Destroy Comment', [comment.profile, comment],
				 method: :delete,
				 data: { confrim: 'Are you sure?' } %>
</p>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [ @profile, @profile.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Website</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_for @profile, :html => { :multipart => true } do |form| %>
 
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@profile.errors.count, "error") %> prohibited
        this profile from being saved:
      </h2>
      <ul>
        <% @profile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :flname %><br>
    <%= form.text_field :flname %>
  </p>
 
  <p>
    <%= form.label :subjects %><br>
    <%= form.text_area :subjects %>
  </p>

  <p>
    <%= form.label :age %><br>
    <%= form.text_area :age %>
  </p>

  <p>
    <%= form.label :phonenumber %><br>
    <%= form.text_area :phonenumber %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.text_area :email %>
  </p>

  <p>
    <%= form.label :experience %><br>
    <%= form.text_area :experience %>
  </p>

  <p>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/profiles/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form' %>
 
<%= link_to 'Back', profile_path %>

app/views/profiles/index.html.erb
<style>

.all_profiles {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  padding: 10px;
}

.profile {
  border: 1px solid black;
  padding: 20px;
  text-align: center;
  margin: 10px;
 
}

</style>

<h1>Tutor Profiles</h1>

<%= link_to 'New Profile', new_profile_path %>
 
 <div class = 'all_profiles'>
  <% @profiles.each do |profile| %>
    <div class = 'profile' >
      <h2><%= profile.flname %></h2>
      <h2><%= profile.subjects %></h2>
      <h2><%= profile.age %></h2>
      <h2><%= profile.phonenumber %></h2>
      <h2><%= profile.email %></h2>
      <h2><%= profile.experience %></h2>
      <h2><%= link_to 'Show', profile_path(profile) %></h2>
      <h2><%= link_to 'Edit', edit_profile_path(profile) %></h2>
      <h2><%= link_to 'Destroy', profile_path(profile),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></h2>
    </div>
  <% end %>
</div>

app/views/profiles/new.html.erb
<h1>Create a Profile!</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p>
	<strong>Name</strong>
	<%= @profile.flname %>
</p>

<p>
	<strong>Subjects</strong>
	<%= @profile.subjects %>
</p>

<p>
	<strong>Age</strong>
	<%= @profile.age %>
</p>

<p>
	<strong>Phone Number</strong>
	<%= @profile.phonenumber %>
</p>

<p>
	<strong>Email</strong>
	<%= @profile.email %>
</p>

<p>
	<strong>Experience</strong>
	<%= @profile.experience %>
</p>

<%= image_tag @profile.image.url %>

<h2>Comments</h2>
<%= render @profile.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>


<%= link_to 'Back', profiles_path %>
<%= link_to 'Edit', edit_profile_path(@profile) %>

app/views/resources_page/index.html.erb
<style>

	h1 {
		text-align: center;
	}
	.resources {
		text-align: center;
		display: inline-block;
	}

	.resources ul {
		list-style-type: none;
	}

	#resource {
		border: 1px solid black;
		margin: 25px;
		text-align: center;
		padding: 30px;
		display: inline-block;
		width: 300px;
		
	}
</style>

<h1>Resources Page</h1>

<div class = "resources">
	<ul>
		<li id = 'resource'>Math</li>
		<li id = 'resource'>Science</li>
		<li id = 'resource'>English</li>
		<li id = 'resource'>History</li>
		<li id = 'resource'>Foreign Language</li>
		<li id = 'resource'>Standardized Testing</li>
	</ul>
</div>

app/views/resources_page/show.html.erb
<h1>Resources</h1>

app/views/welcome/index.html.erb
<style>
.header {
	background-color: #595a5b;
	top: 0;
	width: 100%;
	text-align: center;
	font-family: "Gill Sans", sANS-serif;

}
.header a {
	display: block;
	padding: 30px 20px;
	color: white;
	font-size: 30px;
	}
.header li {
	display: inline-block;
	margin-right: 25px;
	text-align: center;
}
.welcome h1 {
	font-size: 45px;

}
.welcome p {
	font-size: 25px;

}
.welcome {
	text-align: center;
	width: auto;
	font-family: "Helvetica", sANS-serif;

}
a {
	text-decoration: none;
	color: #2B96F1;	
}
a:visted {
	text-decoration: none;
	color: inherit;
}

#tree {
	margin: auto;
	display: block;
	width: 40%;
}

</style>

<div class = 'header'>
	<ul>
		<li><%= link_to 'Profiles', controller: 'profiles' %></li>
		<li><%= link_to 'Resources', controller: 'resources_page' %></a></li>
		<li><a href = ''>About</a></li>
	</ul>
</div>

<div class = 'welcome'>
	<h1>Welcome</h1>

	<p>The goal of this website is to facilitate the connection between tutors and those looking for tutors. We hope to bring you find qualified tutors near you. If you are looking for a tutor, go to the following link to find a list of <a href = "../profiles#index">tutors</a>. If you are looking to register as a tutor, click <a href = "../profiles/new">here</a>.</p>
</div>

<div id = 'tree'>
	<%= image_tag("tree1.png") %>
</div>